# site settings
title: Zhang
subtitle: Zewei
email: youremailaddress@gmail.com
description: I am a professional softeware engineer and a freelance singer/producer.
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url: https://github.com/JoeyNotCodeMonkey
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
